### ISSUE TITLE
Asset precompile fails with undefined method `column_attributes'

### ISSUE THREAD

**Issue by archonic** [kjayma/surveyor_gui#40]
I didn't see anything locally, but this is what happens when pushing to Heroku:

    remote: -----> Preparing app for Rails asset pipeline
    remote:        Running: rake assets:precompile
    remote:        rake aborted!
    remote:        NoMethodError: undefined method `column_attributes' for #<struct PermittedParams params=nil>
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/lib/surveyor_gui/models/column_methods.rb:13:in `block in <module:ColumnMethods>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `class_eval'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/concern.rb:120:in `append_features'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/app/models/column.rb:2:in `include'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/app/models/column.rb:2:in `<class:Column>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/app/models/column.rb:1:in `<top (required)>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:360:in `require_or_load'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:317:in `depend_on'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:233:in `require_dependency'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/lib/surveyor_gui/engine.rb:24:in `block (2 levels) in <class:Engine>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/lib/surveyor_gui/engine.rb:23:in `each'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/surveyor_gui-0.1.2/lib/surveyor_gui/engine.rb:23:in `block in <class:Engine>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `instance_exec'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:441:in `block in make_lambda'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `call'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:189:in `block in simple'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `call'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:190:in `block in simple'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `call'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:92:in `_run_callbacks'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:734:in `_run_prepare_callbacks'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/callbacks.rb:81:in `run_callbacks'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:83:in `prepare!'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/actionpack-4.2.0/lib/action_dispatch/middleware/reloader.rb:55:in `prepare!'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application/finisher.rb:50:in `block in <module:Finisher>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:30:in `run'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:352:in `initialize!'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/config/environment.rb:5:in `<top (required)>'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `block in require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:240:in `load_dependency'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/activesupport-4.2.0/lib/active_support/dependencies.rb:274:in `require'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:328:in `require_environment!'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/railties-4.2.0/lib/rails/application.rb:443:in `block in run_tasks_blocks'
    remote:        /tmp/build_7025e2961ac33212e9d88b2cedf49b95/vendor/bundle/ruby/2.0.0/gems/sprockets-rails-2.2.2/lib/sprockets/rails/task.rb:64:in `block (2 levels) in define'
    remote:        Tasks: TOP => environment
    remote:        (See full trace by running task with --trace)
    remote:  !
    remote:  !     Precompiling assets failed.

I'm using 0.1.2

**Comment by kjayma** [comment]
Will take a look this week.

**Comment by kjayma** [comment]
Having trouble reproducing.  Was able to build a barebones app (see https://github.com/kjayma/survtest) and successfully deployed to heroku here: https://nameless-citadel-2500.herokuapp.com/surveyor_gui/surveyforms

Please try changing your gemfile to take the latest version of surveyor from github and see if that works:

```
gem 'surveyor_gui', :git => 'git://github.com/kjayma/surveyor_gui.git'
```

If that does not solve the problem, we'll need to dig a little deeper into your app.

**Comment by kjayma** [comment]
One other thought - have you run `heroku run rake db:migrate` recently?

**Comment by archonic** [comment]
I believe it was `heroku run rake db:migrate` that got me around this.
Thanks for the help and sorry I didn't reply sooner!

**Comment by kjayma** [comment]
No problem!  Sorry **I** didn't respond sooner.  Day job keeping me pretty busy :)

**Comment by prusswan** [comment]
This is caused by a load order issue in: https://github.com/kjayma/surveyor_gui/blob/master/lib/surveyor_gui/engine.rb#L13

The permitted params decorator (which defines `PermittedParams.new.column_attributes`) needs to be loaded before the models that reference it.
