### ISSUE TITLE
Questions that are mandatory and dependent on another question do not display

### ISSUE THREAD

**Issue by pkuruppu** [kjayma/surveyor_gui#41]
I created a mandatory question, with two questions that display depending on the answer of the mandatory question. One of these two questions is itself mandatory, while the other is not mandatory:
![screen shot 2015-01-11 at 6 57 10 pm](https://cloud.githubusercontent.com/assets/4656698/5698502/43c7a6fa-99c4-11e4-9958-c2e7a051d040.png)

When I select the answer that is expected to then display the non-mandatory subquestion, it works correctly. If I select the answer that is expected to display the mandatory question, the mandatory question does not appear:
![screen shot 2015-01-11 at 6 57 39 pm](https://cloud.githubusercontent.com/assets/4656698/5698515/6aae95f8-99c4-11e4-83ae-29b540b1c03e.png)

**Comment by pkuruppu** [comment]
In the example above, selecting "Yes" to Question 1 is expected to display Question 2. Selecting "No" to Question 1 is supposed to display Question 3.

**Comment by kjayma** [comment]
OK, will take a look
